Updates for migration/translation settings
rokaszygmantas/PrestaShop pull request #3
Opened 2018-08-03 14:59 UTC by tomas862

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop / 1.7.4.x / 1.6.1.x
| Description?  | Please be specific when describing the PR. <br> Every detail helps: versions, browser/server configuration, specific module/theme, etc.
| Type?         | bug fix / improvement / new feature
| Category?     | FO / BO / CO / IN / WS / TE
| BC breaks?    | Does it break backward compatibility? yes/no
| Deprecations? | Does it deprecate an existing feature? yes/no
| Fixed ticket? | (optional) If this PR fixes a [Forge](http://forge.prestashop.com/) ticket, please add its complete Forge URL.
| How to test?  | Please indicate how to best verify that this PR is correct.

2018-08-03 15:57 UTC, tomas862 reviewed
I believe there might be a better solution in the commit  
 [b972fcf](https://github.com/rokaszygmantas/PrestaShop/pull/3/commits/b972fcf2556678bfb87755b0f7c3b199626c03d3) - If there are no choices I want to display only the error message but do not display the selector itself. In this commit - its how exactly it is done but I'm open for suggestions of improvement here.

2018-08-10 06:36 UTC, rokaszygmantas requested changes

2018-08-10 06:36 UTC, rokaszygmantas commented on src/Core/Form/ChoiceProvider/NonInstalledLocalizationChoiceProvider.php
> +        $languages = $this->languagePackLoader->getLanguagePackList();
why not make this return an `array` consistently, so you don't have to care about it being `null` later on

2018-08-10 06:36 UTC, rokaszygmantas commented on src/Core/Language/Pack/Loader/RemoteLanguagePackLoader.php
> +class RemoteLanguagePackLoader implements LanguagePackLoaderInterface
`final`

2018-08-10 06:36 UTC, rokaszygmantas commented on src/PrestaShopBundle/Controller/Admin/TranslationsController.php
> +            $response->deleteFileAfterSend($shouldDelete = true);
`$shouldDelete = true` -> `true`

2018-08-10 06:52 UTC, rokaszygmantas requested changes

2018-08-10 06:52 UTC, rokaszygmantas commented on src/Core/Form/ChoiceProvider/NonInstalledLocalizationChoiceProvider.php
> +        if (!empty($languages)) {
if `$languages` is always an array there is no need to check if it's `!empty`

2018-08-10 06:58 UTC, merged